#.github/workflows/prsk-cheering.yml
name: PR prsk cheering

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  set-prsk-label-and-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Set prsk label and comments
        uses: narumikr/link-sekai-actions/prsk-cheering@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}